[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "popidd-sveil"
version = "0.0.1"
description = "POPIDD's Sveil: A tool for anonymising histopathology slides"
readme = "README.md"
license = {text = "Apache 2.0"}
requires-python = ">=3.10"
authors = [
    {name = "Ferran Cardoso Rodriguez", email = "ferran.cardoso@icr.ac.uk"}
]
keywords = [
  "anonymisation",
  "de-identification",
  "digital-pathology",
  "histopathology",
  "whole-slide-image",
  "wsi",
  "svs",
  "ndpi",
  "tiff",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "imagecodecs>=2025.3.30",
    "pillow>=12.3.0",
    "tifffile>=2025.5.10",
]

[dependency-groups]
dev = [
    "ipykernel",
    "nbdev",
    "pytest",
    "pytest-cov",
    "pre-commit",
    "ruff",
    "matplotlib>=3.10.9",
]

[project.urls]
Documentation = "https://integratedpathologyunit-icr.github.io/popidd-sveil/"
Repository = "https://github.com/IntegratedPathologyUnit-ICR/popidd-sveil"
Issues = "https://github.com/IntegratedPathologyUnit-ICR/popidd-sveil/issues"

[tool.nbdev]
lib_path = "popidd_sveil"
nbs_path = "nbs"
doc_path = "_docs"
recursive = true
tst_flags = "notest"
clean_flag_re = "all_flag"
git_branch = "main"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "B","UP"]

[tool.ruff.lint.per-file-ignores]
"nbs/*.ipynb" = [
  "E402","F403"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=popidd_sveil --cov-report=html --cov-report=term"

[tool.coverage.run]
branch = true
omit = [
    "*/tests/*",
]
