# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/popidd-sveil",
        "doc_host": "https://integratedpathologyunit-icr.github.io",
        "git_url": "https://github.com/IntegratedPathologyUnit-ICR/popidd-sveil",
        "lib_path": "popidd_sveil",
    },
    "syms": {
        "popidd_sveil.core": {
            "popidd_sveil.core.AmbiguousLabelError": (
                "core.html#ambiguouslabelerror",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.AnonymizationResult": (
                "core.html#anonymizationresult",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.ImageReplacement": (
                "core.html#imagereplacement",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.LabelLocation": ("core.html#labellocation", "popidd_sveil/core.py"),
            "popidd_sveil.core.LabelNotFoundError": (
                "core.html#labelnotfounderror",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.OperationMode": ("core.html#operationmode", "popidd_sveil/core.py"),
            "popidd_sveil.core.OutputExistsError": (
                "core.html#outputexistserror",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.PageInfo": ("core.html#pageinfo", "popidd_sveil/core.py"),
            "popidd_sveil.core.ReplacementImageError": (
                "core.html#replacementimageerror",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.SlideFormat": ("core.html#slideformat", "popidd_sveil/core.py"),
            "popidd_sveil.core.SlideInfo": ("core.html#slideinfo", "popidd_sveil/core.py"),
            "popidd_sveil.core.SveilError": ("core.html#sveilerror", "popidd_sveil/core.py"),
            "popidd_sveil.core.UnsafeSegmentError": (
                "core.html#unsafesegmenterror",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.UnsupportedLabelEncodingError": (
                "core.html#unsupportedlabelencodingerror",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.UnsupportedSlideError": (
                "core.html#unsupportedslideerror",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core._as_int_tuple": ("core.html#_as_int_tuple", "popidd_sveil/core.py"),
            "popidd_sveil.core._description_identifies_label": (
                "core.html#_description_identifies_label",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core._enum_name": ("core.html#_enum_name", "popidd_sveil/core.py"),
            "popidd_sveil.core._normalise_description": (
                "core.html#_normalise_description",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core._slide_format": ("core.html#_slide_format", "popidd_sveil/core.py"),
            "popidd_sveil.core._tag_value": ("core.html#_tag_value", "popidd_sveil/core.py"),
            "popidd_sveil.core._write_zeros": ("core.html#_write_zeros", "popidd_sveil/core.py"),
            "popidd_sveil.core.apply_replacement": (
                "core.html#apply_replacement",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.aspect_ratios_match": (
                "core.html#aspect_ratios_match",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.create_blank_jpeg": (
                "core.html#create_blank_jpeg",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.default_output_path": (
                "core.html#default_output_path",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.describe_label_candidate": (
                "core.html#describe_label_candidate",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.find_associated_pages": (
                "core.html#find_associated_pages",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.find_label_page": (
                "core.html#find_label_page",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.find_ndpi_label_page": (
                "core.html#find_ndpi_label_page",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.find_pyramid_pages": (
                "core.html#find_pyramid_pages",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.find_svs_label_page": (
                "core.html#find_svs_label_page",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.find_tiff_label_page": (
                "core.html#find_tiff_label_page",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.group_pages_by_aspect_ratio": (
                "core.html#group_pages_by_aspect_ratio",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.inspect_slide": ("core.html#inspect_slide", "popidd_sveil/core.py"),
            "popidd_sveil.core.is_colour_page": (
                "core.html#is_colour_page",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.label_detection_method": (
                "core.html#label_detection_method",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.prepare_output_path": (
                "core.html#prepare_output_path",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.prepare_replacement": (
                "core.html#prepare_replacement",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.remove_label": ("core.html#remove_label", "popidd_sveil/core.py"),
            "popidd_sveil.core.slide_report": ("core.html#slide_report", "popidd_sveil/core.py"),
            "popidd_sveil.core.validate_blank_page": (
                "core.html#validate_blank_page",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.validate_label_page_for_replacement": (
                "core.html#validate_label_page_for_replacement",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.validate_processed_slide": (
                "core.html#validate_processed_slide",
                "popidd_sveil/core.py",
            ),
            "popidd_sveil.core.validate_replacement": (
                "core.html#validate_replacement",
                "popidd_sveil/core.py",
            ),
        }
    },
}
